### PR TITLE
The Wiki Stuff!

### PR DESCRIPTION
**Pull request by moelrobi**
To Create Wiki Entry's in an Community.

### CODE REVIEW

**Comment by moelrobi** [comment]
@felixfong227 but Fetch is only for GET Request or am i wrong?

**Comment by felixfong227** [comment]
@moelrobi Nope, fetch can actually perform all kinds of HTTP request, `GET/POST/PUT/DELETE` you name it.

And in order to send a `POST` request, the following code might work.
```javascript
fetch('https://api.someendpoint.com', {
  method: "POST",
  body: JSON.stringify({
    data: true,
    name: 'string',
  }),
});
```
😉

**Comment by moelrobi** [comment]
Having a Problem that restricts me from switching to the new API Module.

You can't pipe Streams. I tried but it will not work. Uploading is essential and needed for continuing.

Until Patched this PR is begin stopped.

**Comment by felixfong227** [comment]
@moelrobi 
But we have to consider our front-end JavaScript user? they can't just pass in a path variable inside a Browser environment, but what they can pass in is an actual file object, and so as the Node users. So what I'm thinking is instead of grabbing the path as an argument, we grab a actual file object?

Font end JS
```html
<input id="file" type="file" />
<script>
document.querySelector('#id').onchange = (e) => {
  const file = e.target.files[0];
  AminoJS.upload(file);
};
</script>
```

Node:
```javascript
import fs from 'fs-promise';
(async function(){
  const file = await fs.readFile(path);
  AminoJS.upload(file);
})();
```

**Comment by felixfong227** [comment]
Hey @moelrobi , to be honest, do we need to consider our front-end user after all lol?

**Comment by moelrobi** [comment]
@felixfong227 we didnt plan to develop AminoJS for a Frontend User, you just wanted it to be both compatible. Electron works with Node Require but there it would be good for a file Object to be transmiting for upload, but i dont know how to do that.

See Discord for more Infomation (will Private Message you later this day.)

**Comment by akatsukilevi** [comment]
It's no need to consider front-ending programming on the Amino.JS backend
And the upload system will be transmitting the upload-item as a object, no need to worry

**Comment by felixfong227** [comment]
Got ya @moelrobi @akatsukilevi 😉

**Comment by moelrobi** [comment]
Not making it Compatible with Browser. Leaving the old Upload Function. :100:

**Pull request merged**
