### PR TITLE
Create TODO

### PR DESCRIPTION
**Pull request by akatsukilevi**
Made this TODO directly on GitHub to not forget. Will start working on it tomorrow
More things will be added tomorrow. Got far from the project due to school and work. Got free time now, so i will update it to work with the newer versions of Amino

### CODE REVIEW

**Comment by akatsukilevi** [comment]
FAIL test/modules/getUserBlogs.test.js
  ● how the methods should response (With NO false input) › Get a list of user posted blog posts
    expect(received).toBe(expected) // Object.is equality
    
    Expected value to be:
      true
    Received:
      false
      14 |                 Array.isArray(myBlogs.blogs)
      15 |             )
    > 16 |             .toBe(true);
      17 |             expect(myBlogs.error).toBeNull();
      18 |             expect(myBlogs.status).toBe('ok');
      19 |         });
      
      at Object.it (test/modules/getUserBlogs.test.js:16:14)

Some changes happened at the Amino Back-end, will be fixing it tomorrow too

**Review by felixfong227 — COMMENTED** [review]
Great job @akatsukilevi 👍looks like u are going to be BZ for a while 😹 

1) But there is a really annoying test case is falling ☹️hope we can fix it later on
image

2) Is really great to use some sort of todo list to keep track of tasks and due date, but not create a TODO text file, I highly recommend you to use online services named Asnan for your own personal project and such. And next time you might want to use one of our GitHub's project, it works just like Trello but inside GitHub 😉

**Review by moelrobii — CHANGES_REQUESTED** [review]
a) no need for a todo file directly in the repo for that we can use the Github Projects Board. (maybe create a new board for this?), anyway i will close this and add these to a Feature Board. :D

b) i will take a look to the Testcase soon once github restores all services. i will open a issue to that.

**Comment by moelrobii** [comment]
Please leave the Branch and only delete once the Project board update is done.

**Pull request closed without merging**
