### PR TITLE
Listing Community Users

### PR DESCRIPTION
**Pull request by moelrobi**
### Description
As Feature Request #38 handles with this.

### CODE REVIEW

**Review by moelrobi — COMMENTED** [review]
Should be fine as it is, merging latest dev branch and new Feature.

**Closed and Merged!**

**Comment by moelrobii** [comment]
@felixfong227 
should we get merge this PR already because of #44 our entire Workflow is broken. :-1: :(

**Comment by felixfong227** [comment]
Some how the build fail without any logging 
cb7fafd1-a4ac-4b16-be01-ab5a6efc6d9a

But other than that, everything look 👌 

And plz do expect an other push few hours late for the fixing the fail test case for the user’s blog 😬

**Review by felixfong227 — COMMENTED** [review]
image

Silly me, how can I be such careless 😂🙇‍♂️https://github.com/AminoJS/Amino.JS/commit/b2d23a0eca5e300db5930f8b9412f8ab8abc8b01

Thanks @moelrobii

**Review by moelrobii — APPROVED** [review]
Seems okay by me. But why is the Synk Test Failing?

**Comment by felixfong227** [comment]
Cc: @moelrobii 
image
The Travis build was very successful, but as of right now only Snyk are failing of what I believe is because due to their internal failure

**Pull request merged**
